// flow-typed signature: 84052ac57cf443e8012e8c7342df19e1
// flow-typed version: <<STUB>>/notarealdb_v^0.2.2/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'notarealdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'notarealdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'notarealdb/dist/Collection' {
  declare module.exports: any;
}

declare module 'notarealdb/dist/DataStore' {
  declare module.exports: any;
}

declare module 'notarealdb/dist/Entity' {
  declare module.exports: any;
}

declare module 'notarealdb/dist' {
  declare module.exports: any;
}

declare module 'notarealdb/test/DataStore.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'notarealdb/dist/Collection.js' {
  declare module.exports: $Exports<'notarealdb/dist/Collection'>;
}
declare module 'notarealdb/dist/DataStore.js' {
  declare module.exports: $Exports<'notarealdb/dist/DataStore'>;
}
declare module 'notarealdb/dist/Entity.js' {
  declare module.exports: $Exports<'notarealdb/dist/Entity'>;
}
declare module 'notarealdb/dist/index' {
  declare module.exports: $Exports<'notarealdb/dist'>;
}
declare module 'notarealdb/dist/index.js' {
  declare module.exports: $Exports<'notarealdb/dist'>;
}
declare module 'notarealdb/test/DataStore.test.js' {
  declare module.exports: $Exports<'notarealdb/test/DataStore.test'>;
}
