// flow-typed signature: da0296500d1e080fc67c3995f8d51025
// flow-typed version: <<STUB>>/web-vitals_v^0.2.4/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web-vitals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web-vitals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web-vitals/dist/getCLS' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/getFCP' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/getFID' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/getLCP' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/getTTFB' {
  declare module.exports: any;
}

declare module 'web-vitals/dist' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/lib/bindReporter' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/lib/generateUniqueID' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/lib/getFirstHidden' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/lib/initMetric' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/lib/observe' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/lib/onHidden' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/lib/whenInput' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/types' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals.es5.min' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals.es5.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web-vitals/dist/getCLS.js' {
  declare module.exports: $Exports<'web-vitals/dist/getCLS'>;
}
declare module 'web-vitals/dist/getFCP.js' {
  declare module.exports: $Exports<'web-vitals/dist/getFCP'>;
}
declare module 'web-vitals/dist/getFID.js' {
  declare module.exports: $Exports<'web-vitals/dist/getFID'>;
}
declare module 'web-vitals/dist/getLCP.js' {
  declare module.exports: $Exports<'web-vitals/dist/getLCP'>;
}
declare module 'web-vitals/dist/getTTFB.js' {
  declare module.exports: $Exports<'web-vitals/dist/getTTFB'>;
}
declare module 'web-vitals/dist/index' {
  declare module.exports: $Exports<'web-vitals/dist'>;
}
declare module 'web-vitals/dist/index.js' {
  declare module.exports: $Exports<'web-vitals/dist'>;
}
declare module 'web-vitals/dist/lib/bindReporter.js' {
  declare module.exports: $Exports<'web-vitals/dist/lib/bindReporter'>;
}
declare module 'web-vitals/dist/lib/generateUniqueID.js' {
  declare module.exports: $Exports<'web-vitals/dist/lib/generateUniqueID'>;
}
declare module 'web-vitals/dist/lib/getFirstHidden.js' {
  declare module.exports: $Exports<'web-vitals/dist/lib/getFirstHidden'>;
}
declare module 'web-vitals/dist/lib/initMetric.js' {
  declare module.exports: $Exports<'web-vitals/dist/lib/initMetric'>;
}
declare module 'web-vitals/dist/lib/observe.js' {
  declare module.exports: $Exports<'web-vitals/dist/lib/observe'>;
}
declare module 'web-vitals/dist/lib/onHidden.js' {
  declare module.exports: $Exports<'web-vitals/dist/lib/onHidden'>;
}
declare module 'web-vitals/dist/lib/whenInput.js' {
  declare module.exports: $Exports<'web-vitals/dist/lib/whenInput'>;
}
declare module 'web-vitals/dist/types.js' {
  declare module.exports: $Exports<'web-vitals/dist/types'>;
}
declare module 'web-vitals/dist/web-vitals.es5.min.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals.es5.min'>;
}
declare module 'web-vitals/dist/web-vitals.es5.umd.min.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals.es5.umd.min'>;
}
